# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MpiRrimPlugin
                                 A QGIS plugin
 DEMからMPI-RRIMを作成します
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-19
        copyright            : (C) 2026 by Y. Iwasa
        email                : yiwasa0607@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Y. Iwasa'
__date__ = '2026-03-19'
__copyright__ = '(C) 2026 by Y. Iwasa'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MpiRrimPlugin class from file MpiRrimPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mpi_rrim_plugin import MpiRrimPluginPlugin
    return MpiRrimPluginPlugin()
